from sqlalchemy import Column, Integer, String, DateTime, Float, Boolean
from sqlalchemy.sql import func
from db import Base

class Curriculum(Base):
    __tablename__ = "curriculums"
    
    id = Column(Integer, primary_key=True, index=True)
    id_okso = Column(Integer, nullable=True)
    id_plan_type = Column(Integer)
    id_disc_cycle = Column(Integer, nullable=True)
    id_training_forms = Column(Integer)
    id_study_period = Column(Integer)
    base_credits = Column(Float, nullable=True)
    var_credits = Column(Float, nullable=True)
    id_curr_constrs = Column(Integer, nullable=True)
    id_indep_work_norms = Column(Integer, nullable=True)
    total_credits = Column(Float, nullable=True)
    is_bach_req = Column(Boolean, default=False)
    is_short = Column(Boolean, default=False)
    id_stage_req = Column(Integer, nullable=True)
    year_enrol = Column(Integer)
    id_parent_curriculum = Column(Integer, nullable=True)
    copy_number = Column(Integer, default=0)
    version_number = Column(Integer, default=0)
    id_copy_reason = Column(Integer, nullable=True)
    id_developer = Column(Integer)
    id_responsible = Column(Integer)
    c2h = Column(Integer)
    c2h_min = Column(Integer)
    c2h_max = Column(Integer)
    last_modified = Column(DateTime)
    created = Column(DateTime, nullable=True)
    remark = Column(String, nullable=True)
    has_ge = Column(Boolean, default=False)
    id_status = Column(Integer)
    is_by_cycles_bad = Column(Boolean, default=False)
    credits = Column(Float)
    publish_date = Column(DateTime)
    fsk_facultet = Column(String, nullable=True)
    id_dean = Column(Integer, nullable=True)
    id_chair_head = Column(Integer, nullable=True)
    id_okso_module = Column(Integer, nullable=True)
    id_okso_profile = Column(Integer, nullable=True)
    sem_start_profile = Column(Integer, nullable=True)
    id_chair = Column(Integer, nullable=True)
    type_bac = Column(Integer)
    id_level = Column(Integer, nullable=True)
    duration_months = Column(Integer)
    fk_project_organization = Column(Integer, nullable=True)
    id_curriculum_protocol = Column(Integer, nullable=True)
    id_wp_resp = Column(Integer, nullable=True)
    pages = Column(Integer, nullable=True)
    id_fgos = Column(Integer, nullable=True)
    fk_foreign_langs = Column(Integer, default=0)
    is_tracks = Column(Boolean, default=False)
    edit_cm_developers = Column(Boolean, default=False)
    id_pdf_doc = Column(Integer, nullable=True)
    id_file_g = Column(Integer, nullable=True)